In [6]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.11.0+cpu


## Introduction to tensors
creating tensors

In [8]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
#number of dimensions
scalar.ndim

0

In [10]:
# get tensor back as python int
scalar.item()

7

In [11]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [14]:
# Matrix
matrix = torch.tensor(([7,8],
                     [9,10]))
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
matrix.ndim

2

In [16]:
matrix.shape

torch.Size([2, 2])

In [17]:
# Tensor
tensor = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
tensor.ndim

3

In [19]:
tensor.shape

torch.Size([1, 3, 3])

In [20]:
mak = torch.tensor([[[[1,2,3,4],
                     [4,3,2,1],
                     [4,5,6,7]]]])

In [21]:
mak.ndim

4

In [22]:
mak.shape

torch.Size([1, 1, 3, 4])

# Random tensors

why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represnt the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers


In [23]:
#CReate a randm tensor of size (3,4)
randomtensor = torch.rand(3, 4)
randomtensor

tensor([[0.1818, 0.9924, 0.2169, 0.8619],
        [0.5427, 0.3875, 0.3026, 0.9259],
        [0.2845, 0.3115, 0.1034, 0.8954]])

In [24]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height , width, colour channel
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [25]:
# zeros and ones
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
# create a tensor of ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

## CReating a range of tensors and tensors-like


In [28]:
# Use torch.range()
one_toten = torch.arange(start=0, end=19, step=1)
one_toten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18])

## Tensor datatypes
 
 Note: tensor datatypes is one of the 3 big errors you will run into with pytorch and deep learning
 1. Tensor not right datatype
 2. Tensor not right shape
 3. Tensor not on the right device

In [29]:
# create tensor with bit
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations perfromed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor =torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [33]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors

 1. Tensor not right datatype - to do get datatype from tensor, can use tensor.dtype
 2. Tensor not right shape - to do get shape from tensor, can use tensor.shape
 3. Tensor not on the right device - to do get device from tensor, can use tensor.device

In [34]:
## CReate a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9963, 0.4195, 0.9029, 0.1103],
        [0.8385, 0.6899, 0.9629, 0.0251],
        [0.1816, 0.0328, 0.8277, 0.2505]])

In [35]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.4575, 0.1656, 0.7418, 0.6459],
        [0.5136, 0.7394, 0.0097, 0.2323],
        [0.7980, 0.0540, 0.0332, 0.4474]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating Tensors
These operations are often a wonderful dance between:

1. Addition
2. Substraction
3. Multiplication (element-wise)
4. Division
5. Matrix multiplication

In [36]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [37]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [38]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [39]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([-90, -80, -70])

## Matrix multiplication

Two ways of performing 
1. Element wise multiplication
2. Matrix multiplication(dot product)

In [40]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([-9, -8, -7]) * tensor([-9, -8, -7])
Equals: tensor([81, 64, 49])


In [41]:
# Element-wise matrix mutlication
tensor * tensor

tensor([81, 64, 49])

In [42]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(194)

In [43]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 285 µs, sys: 1.06 ms, total: 1.35 ms
Wall time: 1.24 ms


tensor(194)

In [44]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 392 µs, sys: 66 µs, total: 458 µs
Wall time: 509 µs


tensor(194)


## One of the most common errors in deep learning (shape errors)
Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

THe inner dimensions must match:
* (3,2) @ (3,2) wont work
* (2,3) @ (3,2) will work
* (3,2) @ (2,3) will work

2. The resulting matrix has the shape of the outer dimension
* (2,3) @ (3,2) -> (2, 2)
* (3,2) @ (2,3) -> (3, 3)


In [45]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[1.4941, 1.2246, 1.0937],
        [1.1244, 0.8765, 0.8894],
        [1.5749, 1.2467, 1.2179]])

# One of the most common errors in deep learning : shape error  

In [47]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

#torch.matmul(tensor_A, tensor_B) # (this will error)

To fix our Tensor shape issues, we can manipulate the shape of one of our tensoprs using transpose 

Atranspose switches the axes or dimension of a given tensor.

In [48]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [49]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [50]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [51]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

# Finding the min, max, mean, sum etc (tensor aggregation)

In [52]:
# create tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
#find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [55]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [57]:
# find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [58]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))


# Positional min/max

You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the softmax activation function).

In [59]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


# Change tensor datatype

* Reshape - reshape an input tensor to a define shape
* View -  Return a view of an input tensor of certain shape but keeps the same memory as the original tensor
* stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze -  remove all '1' dimension from a tensor
* Unsqueeze - add '1' dimension to our target tensor
* Permute - Return a  view of the input with diemsnion permutted ( swapped) in a certain way

In [62]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [68]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped = x_reshaped.shape

In [69]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [70]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [71]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [76]:
# print(f"Previous tensor: {x_reshaped}")
# print(f"Previous shape: {x_reshaped.shape}")

# # Remove extra dimension from x_reshaped
# x_squeezed = x_reshaped.squeeze()
# print(f"\nNew tensor: {x_squeezed}")
# print(f"New shape: {x_squeezed.shape}")

In [77]:
# print(f"Previous tensor: {x_squeezed}")
# print(f"Previous shape: {x_squeezed.shape}")

# ## Add an extra dimension with unsqueeze
# x_unsqueezed = x_squeezed.unsqueeze(dim=0)
# print(f"\nNew tensor: {x_unsqueezed}")
# print(f"New shape: {x_unsqueezed.shape}")

In [78]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])



# Indexing (selecting data from tensors)
Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

To do so, you can use indexing.

If you've ever done indexing on Python lists or NumPy arrays, indexing in PyTorch with tensors is very similar.

In [79]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [80]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [81]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [82]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [83]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [84]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [85]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [88]:
x[:, 2, 2]

tensor([9])

# PyTorch tensors & NumPy
Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

In [89]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

*Note*: By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).

However, many PyTorch calculations default to using float32.

So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32).

In [90]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [91]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))


And the same rule applies as above, if you change the original tensor, the new numpy_tensor stays the same.

In [92]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take the random out of random)
In short:

start with random numbers -> tensor operations -> try to make better (again and again and again)

In [93]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8456, 0.5750, 0.2621, 0.1719],
        [0.1021, 0.8674, 0.3655, 0.5230],
        [0.6754, 0.8431, 0.3657, 0.2064]])

Tensor B:
tensor([[0.3628, 0.7911, 0.6127, 0.4632],
        [0.4331, 0.6775, 0.4952, 0.2087],
        [0.3692, 0.9067, 0.7552, 0.3109]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [94]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [95]:
# check for GPU access with Pytorch
import torch
torch.cuda.is_available

<function torch.cuda.is_available() -> bool>

In [97]:
#setup  device agnostic code
device  = "cuda" if  torch.cuda.is_available() else 'cpu'
device

'cpu'

In [98]:
# count number of devices
torch.cuda.device_count()

0

# Putting tensors (and models) on the GPU

In [99]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [100]:
tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0')

SyntaxError: invalid syntax (557421429.py, line 1)